version="testnet"
[miner]
address=""
key=""
[rpc]
host="https://127.0.0.1:1234"
auth="admin:123"
syncBlockInterval=10
syncMemoryInterval=1
syncPeerInfoInterval=3600
syncNodeInfoInterval=3600
syncLockedBlockInterval=60
syncInvalidBlockInterval=60
syncMemoryTxStateInterval=300
[api]
listenPort="11360"
[Auth]
secretKey="123456"
[mysql]
user=""
password=""
address=""
dbname=""
prefix=""
maxidleconns=5
maxopenconns=5
[log]
mode="console"
level="debug"
buffersize=1000